// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kltXeq8Jd7RE4mKC1niqbH6mhcs35_U',
    appId: '1:367349792428:web:87890f4c489af5b0706909',
    messagingSenderId: '367349792428',
    projectId: 'africancuisine-b8759',
    authDomain: 'africancuisine-b8759.firebaseapp.com',
    storageBucket: 'africancuisine-b8759.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYdsmBA5lwQea7ZPoqyUnny8Rvd8jiY6s',
    appId: '1:367349792428:android:3c5c4545c3939f6c706909',
    messagingSenderId: '367349792428',
    projectId: 'africancuisine-b8759',
    storageBucket: 'africancuisine-b8759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhl2I6yRAiFtBN6qktQHe4zmm25kG_kGc',
    appId: '1:367349792428:ios:8c90537864d380b0706909',
    messagingSenderId: '367349792428',
    projectId: 'africancuisine-b8759',
    storageBucket: 'africancuisine-b8759.firebasestorage.app',
    iosBundleId: 'com.khestra.africanCuisine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhl2I6yRAiFtBN6qktQHe4zmm25kG_kGc',
    appId: '1:367349792428:ios:2d3aaf34f14754dc706909',
    messagingSenderId: '367349792428',
    projectId: 'africancuisine-b8759',
    storageBucket: 'africancuisine-b8759.firebasestorage.app',
    iosBundleId: 'com.example.africanCuisine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_kltXeq8Jd7RE4mKC1niqbH6mhcs35_U',
    appId: '1:367349792428:web:960e86db8e78c249706909',
    messagingSenderId: '367349792428',
    projectId: 'africancuisine-b8759',
    authDomain: 'africancuisine-b8759.firebaseapp.com',
    storageBucket: 'africancuisine-b8759.firebasestorage.app',
  );

}